<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Ramsey\Uuid\Uuid;

class Book extends Model
{

    final function getShortContent() {
        return Str::words((string) $this['text'], 10);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->local_id = (string)Uuid::uuid4();
        });
    }
}
